DROP TABLE IF EXISTS  USERS cascade ; 
DROP TABLE IF EXISTS  LOCATIONS cascade ; 


CREATE TABLE USERS (
    u_id SERIAL,
    c_name VARCHAR(150),
    p_number VARCHAR(30),
    profile_url VARCHAR(255),
    PRIMARY KEY(u_id) 
);

CREATE TABLE LOCATIONS (
location_id SERIAL NOT NULL,
user_id INT NOT NULL,
c_name VARCHAR(150) NOT NULL,
c_address VARCHAR(255) NOT NULL,
lat FLOAT NOT NULL,
lon FLOAT NOT NULL,
tag TEXT NOT NULL,
PRIMARY KEY (location_id),
FOREIGN KEY(user_id) REFERENCES USERS(u_id)
);